### ISSUE TITLE
Issues running this inside a React component. - Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by jbflow** [jaxcore/bumblebee-hotword#13]
I'm running into some issues as described in the title using this in a ReactJS Component.

I've basically got the quick start code running inside an arrow function which is called from within componentDidMount() - The component is then rendered inside the main App.js and I'm getting this error:

porcupine_worker.js:1 Uncaught SyntaxError: Unexpected token '<'

Also getting the same one from the downsampling_worker.js.

Any help would be greatly appreciated.

**Comment by dsteinman** [comment]
Did you remember to copy the worker files?  Copy that whole directory to your reactjs "public" folder:

https://github.com/jaxcore/bumblebee-hotword/tree/master/bumblebee-workers

I'm pretty sure if the directory isn't there it'll give this error.

**Comment by jbflow** [comment]
Yeah copied them over to public but still getting this error

**Comment by jbflow** [comment]
I remember having this issue when using it inside a django template and I seem to remember having to do some kind of static import, but unsure how to do that in reactjs.

**Comment by dsteinman** [comment]
`porcupine_worker.js:1 Uncaught SyntaxError: Unexpected token '<'`

That error almost certainly means the porcupine.js wasn't found, the webserver is returning an HTML 404 error instead of a JavaScript file.

I just tried to reproduce the error by deleting the bumblebee-workers directory. from one of the example.  And if I open Chrome inspector I can see the response from the server is the HTML error rather than the Javascript code:

<img width="1437" alt="Screen Shot 2020-08-29 at 6 09 08 PM" src="https://user-images.githubusercontent.com/3894317/91646970-242e7200-ea23-11ea-9224-f2f11a643bf2.png">

Double check the which path the porcupine_worker.js file is loading.

**Comment by jbflow** [comment]
![image](https://user-images.githubusercontent.com/60370472/91648057-e1888c00-ea5a-11ea-91e2-3c2f1b1d8a14.png)

Yeah I think you're right - I've tried various combinations of the setting the path to the worker, moving the folder/scripts around. Could it be that the Component is inside a components folder and then being rendered as a child of my main App.js

**Comment by jbflow** [comment]
ignore the $ sign that just happened when I took the screenshot.

**Comment by dsteinman** [comment]
Try adding this to your package.json, it might fix it:
```
"homepage": ".",
```

Also make sure you can load the JS file directly: http://localhost:3000/bumblebee-workers/porcupine_worker.js

**Comment by jbflow** [comment]
No different unfortunately - And I trying to access it directly doesn't do anything either. I'm starting to think its something to do with the bundler

**Comment by dsteinman** [comment]
If your project is not too big, you could start with one of these examples, an

https://github.com/jaxcore/bumblebee-hotword/tree/master/examples

**Comment by dsteinman** [comment]
Yeah if the JS file at http://localhost:3000/bumblebee-workers/porcupine_worker.js doesn't work then there's no way it will work.

If your project is not too big you could start with one of the examples here:

https://github.com/jaxcore/bumblebee-hotword/tree/master/examples

And then copy all your code to that structure.  Those examples are written with React and do work.

**Comment by jbflow** [comment]
Awesome thanks for your help, I'm going to look at this today - the frontend isn't that big yet so this could be an option.

**Comment by dsteinman** [comment]
Yeah it probably is a small configuration error that might be hard to spot.  In any case I'll close this ticket.
