### ISSUE TITLE
New WASM hotwords

### ISSUE THREAD

**Issue by lawrencenull** [jaxcore/bumblebee-hotword#14]
I just wanted to let you know that new hotwords have been open-sourced:

1. Computer
2. Alexa
3. Hey Google
4. OK Google
5. Hey Siri
6. Jarvis

https://github.com/Picovoice/porcupine/tree/master/resources/keyword_files/wasm

**Comment by dsteinman** [comment]
Awesome, I appreciate the heads up!  I kind of stalled out on this voice project but this would be worth upgrading for.  I practically begged Picovoice to open source the "computer" hotword in the past and they weren't too receptive.

**Comment by lawrencenull** [comment]
They may have added it just for you. It's one I've been waiting on too.

**Comment by dsteinman** [comment]
I did the upgrade this morning, it's been published to npm as v0.2.0
