### ISSUE TITLE
Custom Wake word

### ISSUE THREAD

**Issue by scredii** [jaxcore/bumblebee-hotword#2]
Hi, 

How to import custom wake word please ?

Thanks

**Comment by scredii** [comment]
Solution: xxd -i -g 1 {path/of/model.ppn} to convert file and add result in bumblebee.js hotwords object

**Comment by dsteinman** [comment]
Yup that's exactly the command I used to import the models from Porcupine.

**Comment by Riley-Brown** [comment]
> Yup that's exactly the command I used to import the models from Porcupine.

Does the model from Porcupine have to be WASM platform? I tried converting a custom wake word linux ppn file using @scredii's solution and added it to the hotwords object, but am getting errors when running

```
porcupine.js:70 Uncaught Error: failed to initialize porcupine.
    at Object.create (porcupine.js:70)
    at process (porcupine_worker.js:37)
    at onmessage (porcupine_worker.js:10)
```

```
[ERROR] keyword file has incorrect format or belongs to a different platform (pv_porcupine.js:676)
[ERROR] loading keyword file #0 failed with 'INVALID_ARGUMENT' (pv_porcupine.js:676)
```

**Comment by dsteinman** [comment]
Yeah, the JS version of Porcupine requires the wasm version of the hotwords.  You'd probably have to purchase the hotword from Picovoice to get a wasm version.

I wish they'd provide some more general purpose ones for open source projects to use, like "Computer" and "Jarvis".

**Comment by Riley-Brown** [comment]
Thanks for the response, I figured so. I submitted a form for the enterprise license. Hopefully I can try their custom WASM platform soon as it seems to be exactly what I'm looking for
